name: Release::ghpm

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  ghpm_build:
    permissions:
      contents: write 
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'clone code into github runner'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Setup Go' 
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: 'Install dependencies'
        run: go mod download

      - name: 'build linux/amd64'
        run: |
          GOOS=linux GOARCH=amd64 go build -v -o ${{ github.repository }}-linux-amd64 ./cmd/ghpm/main.go

      - name: 'build linux/arm64'
        run: |
          GOOS=linux GOARCH=arm64 go build -v -o ${{ github.repository }}-linux-arm64 ./cmd/ghpm/main.go

      - name: 'build darwin/amd64'
        run: |
          GOOS=darwin GOARCH=amd64 go build -v -o ${{ github.repository }}-darwin-amd64 ./cmd/ghpm/main.go

      - name: 'build darwin/arm64'
        run: |
          GOOS=darwin GOARCH=arm64 go build -v -o ${{ github.repository }}-darwin-arm64 ./cmd/ghpm/main.go

      - name: 'github release'
        uses: softprops/action-gh-release@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ github.repository }}-linux-amd64
            ${{ github.repository }}-linux-arm64
            ${{ github.repository }}-darwin-amd64
            ${{ github.repository }}-darwin-arm64
          make_latest: 'true'
          generate_release_notes: true
          token: ${{ env.GITHUB_TOKEN }}
